name: songify_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.4
  http: ^1.6.0
  jiosaavn: ^0.1.1
  just_audio: ^0.10.6
  just_audio_background: ^0.0.1-beta.17
  on_audio_query: ^2.9.0
  permission_handler: ^12.0.3
  provider: ^6.1.5+1
  random_avatar: ^0.0.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo_black_bg_padded.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/logo_padded.png"
  remove_alpha_ios: true
